name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-lint:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5 # Upgraded to resolve Node execution deprecation warnings

      - name: Install Kubeconform Natively on Runner Linux Layer
        run: |
          echo "==== Downloading Verified Kubeconform Linux Binary ===="
          wget https://github.com
          tar -xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Run Kubernetes Manifest Validation
        run: |
          echo "==== Starting Structural Manifest Validation ===="
          kubeconform -strict -summary k8s/application.yaml

  build-and-push:
    name: Build & Register Image
    needs: validate-and-lint # Blocks assembly task routes if structural lint steps fail
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5 # Upgraded to align runtime platforms cleanly

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:${{ github.sha }}
